In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.2.0
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.2.1
numpy 1.18.5
pandas 1.0.4
sklearn 0.23.1
tensorflow 2.2.0
tensorflow.keras 2.3.0-tf


In [2]:
# https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt
#文件已经下载好了
input_filepath = "./shakespeare.txt"
text = open(input_filepath, 'r').read()

print(len(text))
print(text[0:100])

1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [3]:
# 1. generate vocab
# 2. build mapping char->id
# 3. data -> id_data  把数据都转为id
# 4. abcd -> bcd<eos>  预测下一个字符生成的模型，也就是输入是a，输出就是b

#去重，留下独立字符，并排序
vocab = sorted(set(text))
print(len(vocab))
print(vocab)

65
['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [4]:
for idx,char in enumerate(['how','are','you']):
    print(idx,char)

0 how
1 are
2 you


In [5]:
#每个字符都编好号，enumerate对每一个位置编号，生成的是列表中是元组，下面字典生成式
char2idx = {char:idx for idx, char in enumerate(vocab)}
print(char2idx)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [6]:
# 把vocab从列表变为ndarray
idx2char = np.array(vocab)
print(idx2char)

['\n' ' ' '!' '$' '&' "'" ',' '-' '.' '3' ':' ';' '?' 'A' 'B' 'C' 'D' 'E'
 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W'
 'X' 'Y' 'Z' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o'
 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [7]:
#把字符都转换为id
text_as_int = np.array([char2idx[c] for c in text])
print(text_as_int.shape)
print(len(text_as_int))
print(text_as_int[0:10])
print(text[0:10])

(1115394,)
1115394
[18 47 56 57 58  1 15 47 58 47]
First Citi


In [8]:
#把输入和输出分配好
def split_input_target(id_text):
    """
    abcde -> abcd, bcde,输入是abcd，输出是bcde
    """
    return id_text[0:-1], id_text[1:]

#把id text转换为 dataset
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
seq_length = 100
#做一个batch，seq_length + 1目的是我们输入是5个字符时，输出是4，drop_remainder
# 是最后不够就丢掉，这个batch是把字变为句子，一个句子是101个字符
seq_dataset = char_dataset.batch(seq_length + 1,
                                 drop_remainder = True)
for ch_id in char_dataset.take(2):
    print(ch_id, idx2char[ch_id.numpy()])

# # seq_dataset 每一个都是句子，对应id，取两个句子看看
for seq_id in seq_dataset.take(2):
    print(seq_id)
    print(repr(''.join(idx2char[seq_id.numpy()])))

tf.Tensor(18, shape=(), dtype=int64) F
tf.Tensor(47, shape=(), dtype=int64) i
tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59  1], shape=(101,), dtype=int64)
'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
tf.Tensor(
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1 49], shape=(101,), dtype=int64)
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'


In [9]:
#然后通过split_input_target函数来对seq_dataset做映射，得到输入，输出
seq_dataset = seq_dataset.map(split_input_target)

for item_input, item_output in seq_dataset.take(2):
    print(item_input)
    print(item_output)
print(seq_dataset)

tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59], shape=(100,), dtype=int64)
tf.Tensor(
[47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43  1
 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43 39
 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49  6
  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0
 37 53 59  1], shape=(100,), dtype=int64)
tf.Tensor(
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 

In [10]:
batch_size = 64
buffer_size = 10000
#这个batch是真正的batch，上一个batch是把字变为句子,buffer_size是从数据集拿那么多元素
seq_dataset = seq_dataset.shuffle(buffer_size).batch(
    batch_size, drop_remainder=True)
print(seq_dataset)

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>


In [11]:
vocab_size = len(vocab)
embedding_dim = 256  #资料比较小，所以dim可以设大一些
rnn_units = 1024

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = keras.models.Sequential([
        keras.layers.Embedding(vocab_size, embedding_dim,
                               batch_input_shape = [batch_size, None]),
        #return_sequences是指要返回一个序列，也就是所有输出，而不是最后一个
        keras.layers.SimpleRNN(units = rnn_units,
                               stateful = True,#是否把上一批最后返回的状态添加到下一批作为输入
                               recurrent_initializer = 'glorot_uniform',
                               return_sequences = True),
        #全连接层，为什么最后一层全连接层的输出是vocab_size
        keras.layers.Dense(vocab_size),
    ])
    return model

model = build_model(
    vocab_size = vocab_size,
    embedding_dim = embedding_dim,
    rnn_units = rnn_units,
    batch_size = batch_size)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (64, None, 256)           16640     
_________________________________________________________________
simple_rnn (SimpleRNN)       (64, None, 1024)          1311744   
_________________________________________________________________
dense (Dense)                (64, None, 65)            66625     
Total params: 1,395,009
Trainable params: 1,395,009
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.variables

[<tf.Variable 'embedding/embeddings:0' shape=(65, 256) dtype=float32, numpy=
 array([[ 0.02793999, -0.03658294, -0.0463387 , ..., -0.03437217,
         -0.02985407,  0.02961728],
        [-0.01269472,  0.00964025,  0.02948172, ..., -0.02079008,
         -0.01866575,  0.04210179],
        [-0.04947106, -0.03557316,  0.04856269, ..., -0.01836097,
         -0.03203521,  0.03027678],
        ...,
        [ 0.02937416, -0.01821499, -0.02430872, ...,  0.02276203,
          0.01273897, -0.04667136],
        [ 0.0394764 ,  0.02699542,  0.00232515, ..., -0.03269802,
          0.0066206 , -0.01468482],
        [-0.0367226 ,  0.04829288, -0.01489383, ...,  0.02807249,
          0.03938459, -0.04228207]], dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/kernel:0' shape=(256, 1024) dtype=float32, numpy=
 array([[ 0.05350012, -0.03856803, -0.01241282, ...,  0.01006741,
          0.04081152, -0.05083002],
        [ 0.03917663,  0.02819687, -0.01498577, ..., -0.01558059,
          0.06137523

In [18]:
for input_example_batch, target_example_batch in seq_dataset.take(1):
    #把model当函数来用，实际是调用类的call方法
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape)

(64, 100, 65)


In [19]:
example_batch_predictions[0][0]

<tf.Tensor: shape=(65,), dtype=float32, numpy=
array([ 4.02087793e-02,  2.19836310e-02, -1.17950350e-01, -1.64357767e-01,
        1.77378021e-02, -4.06723842e-02,  8.38512182e-02, -3.84648815e-02,
        8.01891088e-04, -8.14993307e-02, -1.23511918e-01, -2.22381819e-02,
       -2.48894960e-01, -3.00578289e-02,  2.15509087e-02, -1.66795909e-01,
       -1.61240265e-01,  1.07610144e-01, -4.09748517e-02, -4.01704013e-02,
       -1.70790982e-02, -2.02729747e-01,  1.45160705e-01,  1.81379288e-01,
       -6.57880306e-02, -9.29097086e-03, -2.12056592e-01,  1.16616622e-01,
        1.73387140e-01,  7.05407038e-02,  1.18062064e-01, -5.83287440e-02,
       -1.00314915e-02,  2.40072012e-02,  2.20371962e-01, -6.97887912e-02,
       -2.91380644e-01,  1.22387514e-01, -1.54431403e-01,  8.35303590e-02,
        1.10534966e-01,  1.83799863e-03, -2.11537033e-02, -6.74242377e-02,
       -1.15898103e-02, -1.39257878e-01, -3.38628888e-06,  4.68481854e-02,
        3.65489945e-02,  2.54587561e-01,  1.49396032e

In [20]:
example_batch_predictions[0]

<tf.Tensor: shape=(100, 65), dtype=float32, numpy=
array([[ 0.04020878,  0.02198363, -0.11795035, ...,  0.13698341,
         0.14980823, -0.00966655],
       [-0.19906208, -0.11831973, -0.05956767, ..., -0.2501107 ,
        -0.02149638,  0.07520784],
       [ 0.016205  ,  0.0175315 ,  0.07422484, ...,  0.10957035,
        -0.10925577, -0.20637608],
       ...,
       [-0.119777  ,  0.0235826 , -0.0141993 , ...,  0.03001917,
         0.06553605,  0.17397119],
       [-0.09178037, -0.01082591, -0.03285379, ..., -0.00762922,
        -0.04364044, -0.03222005],
       [-0.07101175,  0.00400396, -0.16647029, ..., -0.5924277 ,
        -0.2255093 ,  0.24154812]], dtype=float32)>

In [21]:
# random sampling.
# greedy, random.
#logits是计算分类任务之前，没有经过softmax的那个值就是logits，把第一个样本输进去
# tf.random.categorical从分类分布中抽取样本,随机为了每次写文章有差异
print(example_batch_predictions[0][0])
print('-'*100)
sample_indices = tf.random.categorical(
    logits = example_batch_predictions[0], num_samples = 1,seed=1)
print(sample_indices)#这里的维度是（100,1）
print('-'*100)
# # (100, 1) -> (100, )  调用squeeze 去除1的维度，变为100的向量
sample_indices = tf.squeeze(sample_indices, axis = -1)
print(sample_indices)

tf.Tensor(
[ 4.02087793e-02  2.19836310e-02 -1.17950350e-01 -1.64357767e-01
  1.77378021e-02 -4.06723842e-02  8.38512182e-02 -3.84648815e-02
  8.01891088e-04 -8.14993307e-02 -1.23511918e-01 -2.22381819e-02
 -2.48894960e-01 -3.00578289e-02  2.15509087e-02 -1.66795909e-01
 -1.61240265e-01  1.07610144e-01 -4.09748517e-02 -4.01704013e-02
 -1.70790982e-02 -2.02729747e-01  1.45160705e-01  1.81379288e-01
 -6.57880306e-02 -9.29097086e-03 -2.12056592e-01  1.16616622e-01
  1.73387140e-01  7.05407038e-02  1.18062064e-01 -5.83287440e-02
 -1.00314915e-02  2.40072012e-02  2.20371962e-01 -6.97887912e-02
 -2.91380644e-01  1.22387514e-01 -1.54431403e-01  8.35303590e-02
  1.10534966e-01  1.83799863e-03 -2.11537033e-02 -6.74242377e-02
 -1.15898103e-02 -1.39257878e-01 -3.38628888e-06  4.68481854e-02
  3.65489945e-02  2.54587561e-01  1.49396032e-01  2.89040148e-01
  2.24233866e-01  1.56427920e-02  9.21608508e-02 -7.65578598e-02
 -5.66843487e-02 -5.99736758e-02 -5.75611293e-02 -3.30605805e-02
 -7.38147572e-

In [27]:
#理解random.categorical，虽然是随机的，但是还是偏向于概率较大的值
#num_samples，意味着我们搞几次抽样
for i in tf.range(5):
    samples = tf.random.categorical([[4.0,2.0,2.0,2.0,1.0]], 3)
    tf.print(samples)

[[0 0 0]]
[[2 1 0]]
[[0 0 0]]
[[0 1 0]]
[[0 0 2]]


In [43]:
print("Input: ", repr("".join(idx2char[input_example_batch[0]])))
print()
print("Output: ", repr("".join(idx2char[target_example_batch[0]])))
print()
print("Predictions: ", repr("".join(idx2char[sample_indices])))

Input:  " the best is, he lives not in them.\n\nLUCIO:\nFriar, thou knowest not the duke so well as I do:\nhe's a"

Output:  "the best is, he lives not in them.\n\nLUCIO:\nFriar, thou knowest not the duke so well as I do:\nhe's a "

Predictions:  "H.?fizSB?dPdGZzjbepfXcE\n.khzIbgMbySEKRrUDkDpGJnGfTfhuIcJ',IgUUIsMlTOsY:oxuJKllGJj\nBk?jSuT;PKrZhPVITL"


In [28]:
# from_logits是否预期为对数张量。默认情况下，我们假设对概率分布进行编码
# logits表示网络的直接输出 。没经过sigmoid或者softmax的概率化。
# from_logits=False就表示把已经概率化了的输出，重新映射回原值。log（p/(1-p)）
def loss(labels, logits):
    return keras.losses.sparse_categorical_crossentropy(
        labels, logits, from_logits=True)

model.compile(optimizer = 'adam', loss = loss)
example_loss = loss(target_example_batch, example_batch_predictions)
print(example_loss.shape)
print(example_loss.numpy().mean())  #看下样例的loss

(64, 100)
4.175256


In [ ]:
#定义一个文件夹，保存模型
output_dir = "./text_generation_checkpoints"
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
checkpoint_prefix = os.path.join(output_dir, 'ckpt_{epoch}')
checkpoint_callback = keras.callbacks.ModelCheckpoint(
    filepath = checkpoint_prefix,
    #只保存权重的值
    save_weights_only = True)

epochs = 100
history = model.fit(seq_dataset, epochs = epochs,
                    callbacks = [checkpoint_callback])


Epoch 1/100
172/172 [==============================] - 195s 1s/step - loss: 2.7963
Epoch 2/100
172/172 [==============================] - 221s 1s/step - loss: 2.0113
Epoch 3/100
172/172 [==============================] - 248s 1s/step - loss: 1.8067
Epoch 4/100
172/172 [==============================] - 241s 1s/step - loss: 1.6766
Epoch 5/100
172/172 [==============================] - 216s 1s/step - loss: 1.5900
Epoch 6/100
172/172 [==============================] - 189s 1s/step - loss: 1.5278
Epoch 7/100
172/172 [==============================] - 178s 1s/step - loss: 1.4836
Epoch 8/100
172/172 [==============================] - 163s 950ms/step - loss: 1.4484
Epoch 9/100
172/172 [==============================] - 160s 932ms/step - loss: 1.4212
Epoch 10/100
172/172 [==============================] - 169s 981ms/step - loss: 1.3962
Epoch 11/100
172/172 [==============================] - 169s 984ms/step - loss: 1.3755
Epoch 12/100
172/172 [==============================] - 164s 955ms/step -

In [ ]:
tf.train.latest_checkpoint(output_dir)

In [46]:
output_dir = "./text_generation_checkpoints"
model2 = build_model(vocab_size,
                     embedding_dim,
                     rnn_units,
                     batch_size = 1)
model2.load_weights(tf.train.latest_checkpoint(output_dir))
#1是一个样本，None是可以变长序列
# model2.build(tf.TensorShape([1, None]))
#下面是文本生成的流程
# start ch sequence A, 
# A -> model -> b  A放入模型后得到b
# A.append(b) -> B
# B(Ab) -> model -> c
# B.append(c) -> C
# C(Abc) -> model -> ...
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 256)            16640     
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (1, None, 1024)           1311744   
_________________________________________________________________
dense_2 (Dense)              (1, None, 65)             66625     
Total params: 1,395,009
Trainable params: 1,395,009
Non-trainable params: 0
_________________________________________________________________


In [47]:
#定义一个函数来实现上面的文本生成流程
def generate_text(model, start_string, num_generate = 1000):
    #这一次输出的是1维的,把字母变为对应的id
    input_eval = [char2idx[ch] for ch in start_string]
    print(input_eval)
    #做一个维度扩展
    input_eval = tf.expand_dims(input_eval, 0)
    print(input_eval)
    text_generated = []
    #对model进行reset，连续调用的时候使用resets_states()
    model.reset_states()
    
    for _ in range(num_generate):
        # 1. model inference -> predictions
        # 2. sample -> ch -> text_generated.
        # 3. update input_eval
        
        # predictions : [batch_size, input_eval_len, vocab_size]
        predictions = model(input_eval)
#         print(predictions.shape)
        #squeeze消掉 batch_size，变为predictions : [input_eval_len, vocab_size]
        predictions = tf.squeeze(predictions, 0)
        # predicted_ids: [input_eval_len, 1]
        # a b c -> b c d
#         print(predictions)
        #把predictions : [input_eval_len, vocab_size]维度数据变为 1个维度
        predicted_id = tf.random.categorical(
            predictions, num_samples = 1)[-1, 0].numpy()  #65个logits得到是什么类别
#         print(predicted_id)
        # 得到预测id后，放入text_generated
        text_generated.append(idx2char[predicted_id])
        # 下面这是是我们原来的公式,为什么没有append作为新的输入,因为那样比较低效
        # s, x -> rnn -> s', y
        input_eval = tf.expand_dims([predicted_id], 0)
#         print(input_eval)
    return start_string + ''.join(text_generated)

new_text = generate_text(model2, "All: ")
print(new_text)


[13, 50, 50, 10, 1]
tf.Tensor([[13 50 50 10  1]], shape=(1, 5), dtype=int32)
All: Mercius, helps, as free
Asmarely sweet Kate; oberts, each in my true and large;
Give me here
I give 't?

BRUTUS:
Godge next way that offerd her by the triave, so it up to face again?
Well, Juliet,
I may for one so sound
To put on a sourchart regreet:
In heard happenies 'Ob?

PETRUCHIO:
Well, my lady, passing that when he sir, we my neckle, asked no more.

CAPULET:
Marsy way hurdly
When he waked the streets of my brother. Thou of marchmy duke?
What, Prince Edward's best.

HENRY BOLINGBROKE:
My graciousl payment and Master; for even it.

PARIS:
And so doth she not told it;
And my goddess 'sarve the curol?

ANGELO:
Lend from the mind peets but to take it to becomest:
He longest measure of thy bosom
justice gave
The admirst me forth to off,
With sixtle, flail that keep alone.

KING LEWIS XINCET:
Well, the world good fast, if thou
My joy, for thy.

DUKE OF YORK:
Fought that he is beating a feverate, or a died,