In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.6.2
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.3.4
numpy 1.19.5
pandas 1.1.5
sklearn 0.24.2
tensorflow 2.6.2
keras.api._v2.keras 2.6.0


In [6]:
# tf.function and auto-graph.
# 自己实现一下elu激活函数,如果scale不为1，那就是selu
def scaled_elu(z, scale=1.0, alpha=1.0):
    # z >= 0 ? scale * z : scale * alpha * tf.nn.elu(z)
    is_positive = tf.greater_equal(z, 0.0)
#     return scale * tf.where(is_positive, z, alpha * tf.nn.elu(z))
    return scale * tf.where(is_positive, z, alpha * (tf.math.exp(z)-1))

# 运行一下，这还是py函数
print(scaled_elu(tf.constant(-3.)))
print(scaled_elu(tf.constant([-3., -2.5])))
print('-' * 50)

# 把py实现的函数变为图实现的函数
# scaled_elu_tf就是图
scaled_elu_tf = tf.function(scaled_elu)
print(scaled_elu_tf(tf.constant(-3.)))
print(scaled_elu_tf(tf.constant([-3., -2.5])))
print('-' * 50)

# 可以通过这种方式找回原来的py函数
print(scaled_elu_tf.python_function is scaled_elu)
print(scaled_elu)
print(scaled_elu_tf)  # tf的函数（图）的执行效率比较高

tf.Tensor(-0.95021296, shape=(), dtype=float32)
tf.Tensor([-0.95021296 -0.917915  ], shape=(2,), dtype=float32)
--------------------------------------------------
tf.Tensor(-0.95021296, shape=(), dtype=float32)
tf.Tensor([-0.95021296 -0.917915  ], shape=(2,), dtype=float32)
--------------------------------------------------
True
<function scaled_elu at 0x7f6b6e0e8268>


In [7]:
# 测试一下性能，100万个数
%timeit scaled_elu(tf.random.normal((1000, 1000)))
%timeit scaled_elu_tf(tf.random.normal((1000, 1000)))

12.3 ms ± 153 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9.23 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
# 1 + 1/2 + 1/2^2 + ... + 1/2^n
# 加了@tf.function装饰后就变为图结果，但是输入类型上不会有变化
@tf.function
def converge_to_2(n_iters):
    total = tf.constant(0.)
    increment = tf.constant(1.)
    for _ in range(n_iters):
        total += increment
        increment /= 2.0
    return total

print(converge_to_2)
print(converge_to_2(20))

tf.Tensor(1.9999981, shape=(), dtype=float32)


In [9]:
# 如何看tf的图的代码
def display_tf_code(func):
    code = tf.autograph.to_code(func)
    from IPython.display import display, Markdown
    display(Markdown('```python\n{}\n```'.format(code)))

In [10]:
# 传普通py函数,返回的是tf图的代码
display_tf_code(scaled_elu)

```python
def tf__scaled_elu(z, scale=None, alpha=None):
    with ag__.FunctionScope('scaled_elu', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        is_positive = ag__.converted_call(ag__.ld(tf).greater_equal, (ag__.ld(z), 0.0), None, fscope)
        try:
            do_return = True
            retval_ = (ag__.ld(scale) * ag__.converted_call(ag__.ld(tf).where, (ag__.ld(is_positive), ag__.ld(z), (ag__.ld(alpha) * (ag__.converted_call(ag__.ld(tf).math.exp, (ag__.ld(z),), None, fscope) - 1))), None, fscope))
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

```

In [15]:
# 这个的前提是去除converge_to_2的装饰
# 因为converge_to_2有@tf.function标注，去掉应该就没问题了
# 或者像下面的处理一样：先找回原来的py函数
# to_code函数的输入是module, class, method, function, traceback, frame, or code object
# 不能是tf function.
display_tf_code(converge_to_2.python_function)

```python
def tf__converge_to(n_iters):
    with ag__.FunctionScope('converge_to_2', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        total = ag__.converted_call(ag__.ld(tf).constant, (0.0,), None, fscope)
        increment = ag__.converted_call(ag__.ld(tf).constant, (1.0,), None, fscope)

        def get_state():
            return (total, increment)

        def set_state(vars_):
            nonlocal increment, total
            (total, increment) = vars_

        def loop_body(itr):
            nonlocal increment, total
            _ = itr
            total = ag__.ld(total)
            total += increment
            increment = ag__.ld(increment)
            increment /= 2.0
        _ = ag__.Undefined('_')
        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(n_iters),), None, fscope), None, loop_body, get_state, set_state, ('total', 'increment'), {'iterate_names': '_'})
        try:
            do_return = True
            retval_ = ag__.ld(total)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

```

In [16]:
# tf要把变量定义在函数外面，不能放里边：避免在函数内重复地申请空间，提高效率
var = tf.Variable(0.)

@tf.function
def add_21():
    return var.assign_add(21) # += 

print(add_21())

tf.Tensor(21.0, shape=(), dtype=float32)


In [17]:
# cube计算立方，py是泛型设计，我们通过input_signature加类型限制可以防止调错

# @tf.function(input_signature=[tf.TensorSpec([None], tf.int32, name='x')])
@tf.function
def cube(z):
    return tf.pow(z, 3)

try:
    print(cube(tf.constant([1., 2., 3.])))
except ValueError as ex:
    print(ex)

print('-'*50)
# 这行没问题
print(cube(tf.constant([1, 2, 3])))
print(cube)

tf.Tensor([ 1.  8. 27.], shape=(3,), dtype=float32)
--------------------------------------------------
tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [19]:
# @tf.function py func -> tf graph
# get_concrete_function -> 给tf.function add input signature -> SavedModel

cube_func_int32 = cube.get_concrete_function(
    tf.TensorSpec([None], tf.int32))
print(cube_func_int32)
print(cube)
print('-'*50)

try:
    print(cube_func_int32(tf.constant([1, 2, 3])))
except Exception as ex:
    print(ex)

ConcreteFunction cube(z)
  Args:
    z: int32 Tensor, shape=(None,)
  Returns:
    int32 Tensor, shape=(None,)
--------------------------------------------------
tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [21]:
# 我们只要看原来函数和新生成的是否一致
# print(cube_func_int32 is cube.get_concrete_function())
print(cube.get_concrete_function(
    tf.constant([1, 2, 3])))
print('-'*50)
print(cube_func_int32)
print('-'*50)
print(cube_func_int32 is cube.get_concrete_function(
    tf.constant([1, 2, 3])))

ConcreteFunction cube(z)
  Args:
    z: int32 Tensor, shape=(3,)
  Returns:
    int32 Tensor, shape=(3,)
--------------------------------------------------
ConcreteFunction cube(z)
  Args:
    z: int32 Tensor, shape=(None,)
  Returns:
    int32 Tensor, shape=(None,)
--------------------------------------------------
False


In [22]:
print(cube_func_int32)
cube_func_int32.graph

ConcreteFunction cube(z)
  Args:
    z: int32 Tensor, shape=(None,)
  Returns:
    int32 Tensor, shape=(None,)


In [23]:
# 看下图定义都有哪些操作,了解即可
cube_func_int32.graph.get_operations()

[<tf.Operation 'z' type=Placeholder>,
 <tf.Operation 'Pow/y' type=Const>,
 <tf.Operation 'Pow' type=Pow>,
 <tf.Operation 'Identity' type=Identity>]

In [24]:
pow_op = cube_func_int32.graph.get_operations()[0]
print(pow_op)

name: "z"
op: "Placeholder"
attr {
  key: "_user_specified_name"
  value {
    s: "z"
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
    }
  }
}



In [25]:
print(list(pow_op.inputs))
print('-'*50)
print(list(pow_op.outputs))


[]
--------------------------------------------------
[<tf.Tensor 'z:0' shape=(None,) dtype=int32>]


In [26]:
# Placeholder用来放输入的地方，2.0中不需要，图中依然保留了
cube_func_int32.graph.get_operation_by_name("z")

<tf.Operation 'z' type=Placeholder>

In [27]:
cube_func_int32.graph.get_tensor_by_name("z:0")

<tf.Tensor 'z:0' shape=(None,) dtype=int32>

In [28]:
# 打印出来看看图信息
cube_func_int32.graph.as_graph_def()

node {
  name: "z"
  op: "Placeholder"
  attr {
    key: "_user_specified_name"
    value {
      s: "z"
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
node {
  name: "Pow/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Pow"
  op: "Pow"
  input: "z"
  input: "Pow/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Identity"
  op: "Identity"
  input: "Pow"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
versions {
  producer: 808
}