In [15]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.6.2
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.3.4
numpy 1.19.5
pandas 1.1.5
sklearn 0.24.2
tensorflow 2.6.2
keras.api._v2.keras 2.6.0


In [16]:
# 内存中构建dataset，初始化dataset
# 切片
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int64>


In [33]:
# 可以做遍历，每一个都是tensor
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [31]:
dataset_comparison = tf.data.Dataset.from_tensors(np.arange(10).repeat(3))
print(dataset_comparison)

<TensorDataset shapes: (30,), types: tf.int64>


In [34]:
for item in dataset_comparison:
    print(item)

tf.Tensor([0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9], shape=(30,), dtype=int64)


In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
type(np.arange(10))

numpy.ndarray

In [39]:
np.arange(10).repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [4]:
dataset1 = dataset.repeat(3)
for item in dataset1:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype

In [5]:
# 1. repeat 重复生成
# 2. batch 分成不同batches

dataset = dataset.repeat(3).batch(7)
print(dataset)
print('-' * 50)

i=0
for item in dataset:
    i=i+1
    print(item)
i

<BatchDataset shapes: (None,), types: tf.int64>
--------------------------------------------------
tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)


5

In [6]:
for i in dataset:
    print(i)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)


In [9]:
d = dataset.repeat(3)
for i in d:
    print(i)
    print('-' * 50)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([8 9], shape=(2,), dtype=int64)
--------------------------------------------------
tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
--------------------------------------------------
tf.Tensor([8 9], shape=(2,), dtype=int64)
-----------------------------------------

In [10]:
# interleave: 作用 https://zhuanlan.zhihu.com/p/97876668
# case: 文件dataset -> 具体数据集
# 这个例子不好，不够直观，有些误导性

dataset2 = dataset.interleave(
    lambda v: tf.data.Dataset.from_tensor_slices(v),  # map_func
    cycle_length = 5,  # cycle_length,每一个cycle提取的个数
    block_length = 6,  # block_length,每一个block的长度
)
print(dataset2)
print('-' * 50)

i=0
for item in dataset2:
    i=i+1
    print(item)
i

<InterleaveDataset shapes: (), types: tf.int64>
--------------------------------------------------
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
t

30

In [24]:
a = tf.data.Dataset.range(1,6) 
b = a.repeat(6)
for i in b:
    print(i)
print('-'*50)

c = tf.data.Dataset.from_tensors(a).repeat(6)
for i in c:
    print(i)
print('-'*50)

# cycle_length是使用了几个block以后，算作一个cycle
# 第一次遇见interleave: 从原Dataset中取出3个元素，然后对其分别应用(之前的盲点)map_func(这里的匿名函数)
# 得到3个新的Dataset对象，然后每个新对象中取4个数据，直到取尽
# 然后再接着从原Dataset中取出3个元素，重复上述步骤（终于通了）
a1 = a.interleave(lambda x: tf.data.Dataset.from_tensors(x).repeat(6),
            cycle_length=3, block_length=4)
for i in a1:
    print(i)
print(a1)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype

In [41]:
type(a)

tensorflow.python.data.ops.dataset_ops.RangeDataset

In [68]:
for i in a:
    print(i)
    a_tmp = tf.data.Dataset.from_tensors(i).repeat(3)
    for j in a_tmp:
        print(j)
print('-'*50)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
--------------------------------------------------


In [46]:
tmp = tf.data.Dataset.from_tensors(a.repeat(6))
for item in tmp:
    print(item)
    print(type(item))
print("-" * 50)
print(tmp)

<_VariantDataset shapes: (), types: tf.int64>
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>
--------------------------------------------------
<TensorDataset shapes: DatasetSpec(TensorSpec(shape=(), dtype=tf.int64, name=None), TensorShape([])), types: DatasetSpec(TensorSpec(shape=(), dtype=tf.int64, name=None), TensorShape([]))>


In [49]:
a2 = tf.data.Dataset.from_tensors(np.arange(6)) 
b2 = a2.repeat(3)
for i in b2:
    print(i)
print('-'*50)

a3 = a2.interleave(lambda x: tf.data.Dataset.from_tensors(x).repeat(6),
            cycle_length=3, block_length=4)
for i in a3:
    print(i)
print(a3)

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
--------------------------------------------------
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
<InterleaveDataset shapes: (6,), types: tf.int64>


In [12]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array(['cat', 'dog', 'fox'])
# 输入的参数是元组的情况下
dataset3 = tf.data.Dataset.from_tensor_slices((x, y))
print(dataset3)

for item_x, item_y in dataset3:
    print(item_x, item_y)

<TensorSliceDataset shapes: ((2,), ()), types: (tf.int64, tf.string)>
tf.Tensor([1 2], shape=(2,), dtype=int64) tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor([3 4], shape=(2,), dtype=int64) tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor([5 6], shape=(2,), dtype=int64) tf.Tensor(b'fox', shape=(), dtype=string)


In [13]:
# 输入的参数是字典的情况下
dataset4 = tf.data.Dataset.from_tensor_slices({"feature1": x,
                                               "label": y})
print(dataset4)
for item in dataset4:
    print(item["feature1"], item["label"])

<TensorSliceDataset shapes: {feature1: (2,), label: ()}, types: {feature1: tf.int64, label: tf.string}>
tf.Tensor([1 2], shape=(2,), dtype=int64) tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor([3 4], shape=(2,), dtype=int64) tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor([5 6], shape=(2,), dtype=int64) tf.Tensor(b'fox', shape=(), dtype=string)


In [14]:
a = tf.data.Dataset.range(1, 6)  # ==> [ 1, 2, 3, 4, 5 ]
print(a)
# NOTE: New lines indicate "block" boundaries.
dataset2 = a.interleave(lambda x: tf.data.Dataset.from_tensors(x).repeat(6),
            cycle_length=2, block_length=4)  # ==> [1, 1, 1, 1,
                                             #      2, 2, 2, 2,
                                             #      1, 1,
                                             #      2, 2,
                                             #      3, 3, 3, 3,
                                             #      4, 4, 4, 4,
                                             #      3, 3,
                                             #      4, 4,
                                             #      5, 5, 5, 5,
                                             #      5, 5]
print(dataset2)
for item in dataset2:
    print(item)

<RangeDataset shapes: (), types: tf.int64>
<InterleaveDataset shapes: (), types: tf.int64>
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor